version: 2

# Define the jobs to be run django tests python:3.10.6

jobs:
     build:
        docker:
        - image: circleci/python:3.10.6
        steps:
        - checkout
        - run:
            name: Install dependencies
            command: |
                python -m venv venv
                . venv/bin/activate
                pip install -r requirements.txt
        - run:
            name: Run tests
            command: |
                . venv/bin/activate
                cd PollsAPI
                python manage.py test

